/**

 * This file is automatically generated.

 * DO NOT EDIT manually

 */



/// <reference path="./manifest.d.ts" />

import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'

import type { InferSharedProps } from '@adonisjs/inertia/types'

import type RoleTransformer from '../../app/users/transformers/role_transformer.ts'

import type TokenTransformer from '../../app/users/transformers/token_transformer.ts'

import type UserTransformer from '../../app/users/transformers/user_transformer.ts'

import type InertiaMiddleware from '#core/middleware/inertia_middleware'



export namespace Data {
  export namespace Users {
    export type Role = InferData<RoleTransformer>

    export namespace Role {
      export type Variants = InferVariants<RoleTransformer>

    }
    export type Token = InferData<TokenTransformer>

    export namespace Token {
      export type Variants = InferVariants<TokenTransformer>

    }
    export type User = InferData<UserTransformer>

    export namespace User {
      export type Variants = InferVariants<UserTransformer>

    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>

}
