import type { AllHooks, IndexGeneratorSourceConfig } from '@adonisjs/assembler/types'
import string from '@adonisjs/core/helpers/string'

type IndexGeneratorAs = Extract<IndexGeneratorSourceConfig, { as: (...args: any[]) => void }>['as']
type IndexGeneratorAsParams = Parameters<IndexGeneratorAs>

interface TransformerInfo {
  name: string
  className: string
  module: string
  importPath: string
}

interface IndexTransformersOptions {
  withSharedProps?: boolean
  inertiaMiddlewareImportPath?: string
}

const indexTransformersHook = (
  options: IndexTransformersOptions = {}
): AllHooks['init'][number] => ({
  run(_parent, _hooks, indexGenerator) {
    indexGenerator.add('transformers', {
      source: 'app',
      glob: ['**/transformers/**/*.ts'],
      filter: (filePath: string, isDir: boolean) => {
        if (isDir) return true
        return filePath.includes('/transformers/') && filePath.endsWith('_transformer.ts')
      },
      output: '.adonisjs/client/data.d.ts',
      as(
        vfs: IndexGeneratorAsParams[0],
        buffer: IndexGeneratorAsParams[1],
        _config: IndexGeneratorAsParams[2],
        helpers: IndexGeneratorAsParams[3]
      ) {
        const filesList = vfs.asList()

        // Group transformers by module
        const byModule = new Map<string, TransformerInfo[]>()

        Object.keys(filesList).forEach((key) => {
          const parts = key.replace(/^\.\//, '').split('/')
          const module = string.pascalCase(parts[0])
          const baseName = parts[parts.length - 1].replace(/_transformer$/, '')
          const name = string.pascalCase(baseName)

          const info: TransformerInfo = {
            name,
            className: `${name}Transformer`,
            module,
            importPath: helpers.toImportPath(filesList[key]),
          }

          const existing = byModule.get(module) || []
          existing.push(info)
          byModule.set(module, existing)
        })

        // Generate file header
        buffer.writeLine('/**')
        buffer.writeLine(' * This file is automatically generated.')
        buffer.writeLine(' * DO NOT EDIT manually')
        buffer.writeLine(' */')
        buffer.writeLine('')
        buffer.writeLine(`/// <reference path="./manifest.d.ts" />`)
        buffer.writeLine(
          `import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'`
        )

        if (options.withSharedProps && options.inertiaMiddlewareImportPath) {
          buffer.writeLine(`import type { InferSharedProps } from '@adonisjs/inertia/types'`)
        }

        // Import each transformer class
        const allTransformers = Array.from(byModule.values()).flat()
        allTransformers.forEach((t) => {
          buffer.writeLine(`import type ${t.className} from '${t.importPath}'`)
        })

        if (options.withSharedProps && options.inertiaMiddlewareImportPath) {
          buffer.writeLine(
            `import type InertiaMiddleware from '${options.inertiaMiddlewareImportPath}'`
          )
        }

        buffer.writeLine('')
        buffer.write('export namespace Data {').indent()

        // Generate namespace per module
        byModule.forEach((transformers, module) => {
          buffer.write(`export namespace ${module} {`).indent()

          transformers.forEach((t) => {
            buffer.writeLine(`export type ${t.name} = InferData<${t.className}>`)
            buffer.write(`export namespace ${t.name} {`).indent()
            buffer.writeLine(`export type Variants = InferVariants<${t.className}>`)
            buffer.dedent().write('}')
          })

          buffer.dedent().write('}')
        })

        // SharedProps at root level
        if (options.withSharedProps && options.inertiaMiddlewareImportPath) {
          buffer.writeLine(`export type SharedProps = InferSharedProps<InertiaMiddleware>`)
        }

        buffer.dedent().write('}')
      },
    })
  },
})

export const indexTransformers = (options: IndexTransformersOptions = {}) => {
  return indexTransformersHook(options)
}

export default indexTransformers
